### ISSUE TITLE
Add Travis CI support

### ISSUE THREAD

**Issue by maxcanna** [adespresso/monkey-tools#13]
Add `.travis.yml` to enable [Travis CI](http://travis-ci.org)
Something like this should suffice:
```yml
language: node_js
node_js:
  - "node"
```
